#+TITLE:Org Capture (WebExt)

This is a web-extension for capturing links, quotes, media, pages, etc. with [[https://orgmode.org/worg/org-contrib/org-protocol.html][org-protocol]].

* Features

1. [[https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox][Hotkeys]]. One for storing links, one for capturing the page (or selected text, if the selection is active).
2. Context menu items for capturing:
   - The current page.
   - Selected text. Optionally, selections can be captured as HTML. You'll want to use this with something like [[https://github.com/alphapapa/org-protocol-capture-html][org-protocol-capture-html]] to translate the HTML to org mode.
   - Media (images, video, etc.). Media can be (optionally) downloaded (through your browser's download manager) before capturing.
3. A browser action button to perform some default action on click (can either store a link to the current page, or initiate a capture).
4. Optionally, capturing a selection will capture the HTML itself. You'll want to use this with something like [[https://github.com/alphapapa/org-protocol-capture-html][org-protocol-capture-html]] to translate the HTML to org mode.

* Contributing & Bug Reports

This is a /forks welcome/ project. I'm open to feedback and fixes, but I built it because I needed it and don't intend on putting any real effort/time into it. This means:

- Forks are _VERY MUCH_ welcome, even encouraged. I don't want to maintain this addon, I just built it because I didn't like the existing ones.
- If a patch/issue would require any amount of work/maintenance on my part to land, I'll likely just close it. Please don't take this as commentary on your code and feel free to fork.
- Do file bug reports, but please keep your expecations low.
- You _can_ file feature requests; I'm always interested in new ideas. But don't disappointed if I close them without much discussion beyond a quick "no thanks"/"not interested".

* Building & Installing

This addon currently only supports Firefox and derivatives. I'm happy to accept patches that support other browsers, but I likely won't do much testing and things may break.

To build, run  ~make build~. You'll need the ~zip~ command.

Before installing, you'll need to either sign the extension, install a version of Firefox that doesn't mandate addon signature validation, or [[https://github.com/Stebalien/firefox-tweak][hack your Firefox install]]. Personally, I'd recommend the second option ([[https://librewolf.net/][LibreWolf]] works great!) then disable ~xpinstall.signatures.required~ in [[about:config]].

* Signing & Distribution

For addon distribution, there are ~make build-webext~ and ~make sign-webext~ commands. However, these require API keys and we're at the mercy of our Mozilla overlords on when addons actually get signed. So...

1. I'm not going to list it on the store (for now).
2. Signed versions will ship when they ship, likely never.

* History

Heavily inspired by both [[https://github.com/sprig/org-capture-extension][Org Capture Extension]] and [[https://github.com/vifon/org-protocol-for-firefox][Org Protocol for Firefox]]. However, the former [[https://github.com/sprig/org-capture-extension/issues/80][required permission]] for every new page captured and the latter wasn't very customizable and required manual clicks to complete a capture.
